### ISSUE TITLE
Keyboard switches

### ISSUE THREAD

**Issue by ghhann** [iNimbleSloth/zx81-mechboard#1]
I ordered your board off of pcbway.  I was looking for specifics on the switches you used?  Is there an Amazon link you could share?  Also is there a part number for the led? 

Best

**Comment by iNimbleSloth** [comment]
Hi, 
Sure, I used these from Amazon - https://www.amazon.co.uk/gp/product/B09WVWZG8F
Gateron ks-9 G PRO Brown. The LED is any SMD size 1206, . I've used these https://www.amazon.co.uk/gp/product/B09VBR4MLC 
The resistor for the LED is on the main ZX81+38 motherboard, just be mindful of that if you are not using that motherboard.

**Comment by ghhann** [comment]
Thank you very much.  I'll be doing this project while recovering from a neurological procedure.  Just to confirm for wasd I use the extended keycap file?   Have you ever thought of doing your keycaps for a spectrum?  I would guess that your keyboard is similar that it could work in a spectrum clone board.  I've been enjoying your videos on YouTube.  Best

**Comment by iNimbleSloth** [comment]
[These are the keycaps that I ordered from WASD](https://www.wasdkeyboards.com/62-key-iso-custom-cherry-mx-keycap-set.html).  There is also this [US ANSI version ](https://www.wasdkeyboards.com/61-key-custom-cherry-mx-keycap-set.html).
I ordered the ISO version as I wanted to use some of the "spare" keys for another project requiring the ISO Enter key.

I got the bank template from them at https://support.wasdkeyboards.com/hc/en-us/articles/115007847008-Download-Template-Files. The template I downloaded was the the [62-Key Intl ISO Layout ](https://support.wasdkeyboards.com/hc/article_attachments/4418291821463/wasd-ai-62-08.20.2021.ai), so not the extended file, just the 62 key version.

[My edited keycap file ](https://github.com/iNimbleSloth/zx81-mechboard/tree/main/keycaps%20layout) has two versions, one that has editable text and the other with "Expanded" in the name is no longer "text", its been converted to graphics as that's what WASD request before uploading the file. I placed both files on Github to give the choice of easily editing the raw text if someone wanted, or just going with the expanded to graphics version.

I've not checked the pinouts of the ZX81 vs ZX Spectrum for the keyboard connections, so don't know if compatible.

I hadn't considered doing a ZX Spectrum clone with mechanical keyboard, but that would be quite fun I think.

Hope you recover from your procedure soon!
