### ISSUE TITLE
STL Files

### ISSUE THREAD

**Issue by JmanNZ** [iNimbleSloth/zx81-mechboard#2]
Could please upload the case STL files. Great keyboard works a treat. I just need a case now :)

**Comment by iNimbleSloth** [comment]
Hi,
Great to hear the keyboard is working for you 😊
I've uploaded a few files. The keyboard only "case" that I printed and used in the keyboard video. I also included a second revision - https://github.com/iNimbleSloth/zx81-mechboard/tree/main/keyboard_only_case

The full case for the ZX81+38 that I printed in the final build video - https://github.com/iNimbleSloth/zx81-mechboard/tree/main/ZX81%2B38%20case
